# Generated by Django 4.2.1 on 2023-06-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('main', 'MAIN'), ('children', 'Children')], default='MAIN', max_length=20),
        ),
    ]
