# Generated by Django 4.2.1 on 2023-06-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_button_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='source_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_buttons', to='core.menu'),
        ),
    ]
