# Generated by Django 4.2.1 on 2023-06-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_broadcast_telegramuser_alter_menu_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
    ]
