# Generated by Django 4.2.1 on 2023-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='sent_users',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
